### ISSUE TITLE
SoundCloud authentication via the default browser

### ISSUE THREAD

**Issue by aleksandar-todorovic** [vincelwt/Nem-Music-Player#1]
During the SoundCloud user authentication:

**Do**

Redirect the user to his default browser and open up the URL where the user will be asked to confirm that he really wants to give the permissions to the app to use his account and allow the user to see the list of permissions that this app needs.

**Don't**

Assume that the users will agree automatically with this.

---
From https://developers.soundcloud.com/docs/api/guide#user-credentials

> Our Terms of Service specify that you must use the Connect with SoundCloud screen unless you have made a separate arrangement with us.

So, you're currently breaking the SoundCloud's ToS.

**Comment by vincelwt** [comment]
Work in progress, will be changed soon. Thanks for reporting.
