### ISSUE TITLE
JS Error: Uncaught TypeError: Cannot set property 'source' of null

### ISSUE THREAD

**Issue by sagidayan** [vincelwt/Nem-Music-Player#2]
While running the app with only GMusic as a source
```(shell)
$ npm start
```

loading screen didn't stop "loading",
I opened the devTools. 
JS Error.  app\js\app.js line 388
**_Uncaught TypeError: Cannot set property 'source' of null_**

![screenshot from 2016-02-21 14-49-07](https://cloud.githubusercontent.com/assets/2984053/13202644/8940afd0-d8aa-11e5-82ec-8fba797c2857.png)

ill fork it and see if a simple "if" statement will fix the issue

nice job!

**Comment by vincelwt** [comment]
Thank's for reporting :)
